/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllGui;

import javax.swing.JFrame;
import user_manager.*;
/**
 *
 * @author user
 */
public class changeAccount extends javax.swing.JFrame {

    user_manager.USERS us;
    user_manager.ChangeAccount ch;
    
    public changeAccount() {
        initComponents();
        this.setSize(1280, 720);
        setLocationRelativeTo(null);
        this.setResizable(false);
       setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabel = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Area = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passExipre = new javax.swing.JTextField();
        passInactive = new javax.swing.JTextField();
        accExipre = new javax.swing.JTextField();
        minNumBetChange = new javax.swing.JTextField();
        maxNumBetChange = new javax.swing.JTextField();
        numOfDayBeforeExipre = new javax.swing.JTextField();
        passEx = new javax.swing.JButton();
        passIn = new javax.swing.JButton();
        accEx = new javax.swing.JButton();
        minNum = new javax.swing.JButton();
        maxNum = new javax.swing.JButton();
        numBeforeEx = new javax.swing.JButton();
        showChanges = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlabel.setText("username");

        username.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Change Account Page");

        clear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        Area.setColumns(20);
        Area.setRows(5);
        jScrollPane1.setViewportView(Area);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("passExipre");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("passInactive");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("accExipre");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("miniNumberBetChange");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("warning before Exp");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("maxiNumberBetChange");

        passExipre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        passExipre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passExipreActionPerformed(evt);
            }
        });

        passInactive.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        accExipre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        minNumBetChange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        maxNumBetChange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        numOfDayBeforeExipre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        passEx.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passEx.setText("passEx");
        passEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passExActionPerformed(evt);
            }
        });

        passIn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passIn.setText("passInactive");
        passIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passInActionPerformed(evt);
            }
        });

        accEx.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        accEx.setText("accExipre");
        accEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accExActionPerformed(evt);
            }
        });

        minNum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minNum.setText("minNumber");
        minNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minNumActionPerformed(evt);
            }
        });

        maxNum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        maxNum.setText("maxNumber");
        maxNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxNumActionPerformed(evt);
            }
        });

        numBeforeEx.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        numBeforeEx.setText("warning before Exp");
        numBeforeEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numBeforeExActionPerformed(evt);
            }
        });

        showChanges.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showChanges.setText("showChanges");
        showChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showChangesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(passInactive)
                                .addComponent(accExipre, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlabel)
                                .addComponent(jLabel2))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passExipre, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passEx)
                        .addGap(26, 26, 26)
                        .addComponent(passIn)
                        .addGap(18, 18, 18)
                        .addComponent(accEx)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minNumBetChange, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxNumBetChange, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numOfDayBeforeExipre, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(minNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(maxNum)
                        .addGap(27, 27, 27)
                        .addComponent(numBeforeEx)
                        .addGap(27, 27, 27)
                        .addComponent(showChanges)))
                .addGap(98, 98, 98)
                .addComponent(clear)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passExipre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(passInactive, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(accExipre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(minNumBetChange, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addComponent(jLabel7))
                            .addComponent(maxNumBetChange, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(numOfDayBeforeExipre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clear)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(passEx)
                                .addComponent(passIn)
                                .addComponent(accEx)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(minNum)
                                    .addComponent(maxNum)
                                    .addComponent(numBeforeEx)
                                    .addComponent(showChanges))))
                        .addGap(48, 48, 48)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
       
         username.setText("");
         passInactive.setText("");
         passExipre.setText("");
         numOfDayBeforeExipre.setText("");
         minNumBetChange.setText("");
         maxNumBetChange.setText("");        
         accExipre.setText("");        
                 
    }//GEN-LAST:event_clearActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Juser().setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void passExipreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passExipreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passExipreActionPerformed

    private void showChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showChangesActionPerformed
        // TODO add your handling code here:
        ch=new ChangeAccount(username.getText().trim());
        Area.setText(ch.ShowChanges());
        
    }//GEN-LAST:event_showChangesActionPerformed

    private void passInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passInActionPerformed
        // TODO add your handling code here:
        ch=new ChangeAccount(username.getText(),Integer.parseInt(passInactive.getText().trim()));
        ch.inActive();
        Area.setText(ch.ShowChanges());
    }//GEN-LAST:event_passInActionPerformed

    private void accExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accExActionPerformed
        // TODO add your handling code here:
        ch=new ChangeAccount(username.getText());
        ch.setDate(accExipre.getText().trim());
        ch.accountExp();
        Area.setText(ch.ShowChanges());
    }//GEN-LAST:event_accExActionPerformed

    private void minNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minNumActionPerformed
        // TODO add your handling code here:
        ch=new ChangeAccount(username.getText(),Integer.parseInt(minNumBetChange.getText().trim()));
        ch.min();
        Area.setText(ch.ShowChanges());
    }//GEN-LAST:event_minNumActionPerformed

    private void maxNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxNumActionPerformed
        // TODO add your handling code here:
        ch=new ChangeAccount(username.getText(),Integer.parseInt(maxNumBetChange.getText().trim()));
        ch.max();
        Area.setText(ch.ShowChanges());
    }//GEN-LAST:event_maxNumActionPerformed

    private void numBeforeExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numBeforeExActionPerformed
        // TODO add your handling code here:
        ch=new ChangeAccount(username.getText(),Integer.parseInt(numOfDayBeforeExipre.getText().trim()));
        ch.warningBeforeExp();
        Area.setText(ch.ShowChanges());
    }//GEN-LAST:event_numBeforeExActionPerformed

    private void passExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passExActionPerformed
        // TODO add your handling code here:
        ch=new ChangeAccount(username.getText(),Integer.parseInt(passExipre.getText().trim()));
        ch.max();
        Area.setText(ch.ShowChanges());
    }//GEN-LAST:event_passExActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changeAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changeAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changeAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changeAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changeAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area;
    private javax.swing.JButton accEx;
    private javax.swing.JTextField accExipre;
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JButton maxNum;
    private javax.swing.JTextField maxNumBetChange;
    private javax.swing.JButton minNum;
    private javax.swing.JTextField minNumBetChange;
    private javax.swing.JButton numBeforeEx;
    private javax.swing.JTextField numOfDayBeforeExipre;
    private javax.swing.JButton passEx;
    private javax.swing.JTextField passExipre;
    private javax.swing.JButton passIn;
    private javax.swing.JTextField passInactive;
    private javax.swing.JButton showChanges;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
